services:
  mystorage:
    build:
      context: .
      dockerfile: ./LimitedStorage/Dockerfile
    ports:
      - "1234:80"
    container_name: "mystorage"

  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./examples:/scripts

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - mystorage

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Change this password
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  sutservice:
    build:
      context: .
      dockerfile: ./SutService/Dockerfile
    ports:
      - "80"
    deploy:
      replicas: 1
      
  nginx:
    image: nginx
    ports:
      - "80:80"  # Expose the port you want to use externally
    depends_on:
      - sutservice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx configuration

volumes:
  grafana_data:
    driver: local